# Generated by Django 5.1.7 on 2025-04-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
