# Generated by Django 5.1.7 on 2025-04-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('post_created', 'Post Created'), ('comment_created', 'Comment Created'), ('like_created', 'Like Created'), ('chat_created', 'Chat Created'), ('message_sent', 'Message Sent'), ('post_deleted', 'Post Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.comment'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.post'),
        ),
    ]
